dependencies:
- name: exposecontroller
  version: 2.3.82
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.82
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: infrastructure
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.5.1
- name: application
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.5.0
- name: activiti-cloud-modeling
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.5.0
  condition: activiti-cloud-modeling.enabled,modeling.enabled
